# Generated by Django 5.0.6 on 2024-10-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(editable=False, max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('organiser', models.CharField(max_length=100)),
                ('sponsor', models.TextField()),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Cultural', 'Cultural'), ('Technical', 'Technical'), ('Other', 'Other')], max_length=20)),
                ('event_datetime', models.DateTimeField()),
                ('one_line_description', models.CharField(max_length=255)),
                ('complete_description', models.TextField()),
                ('eligibility', models.TextField()),
                ('rewards', models.TextField()),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Upcoming', max_length=10)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
